source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CyberGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for futures
pod 'JXCategoryView'
pod 'IQKeyboardManager'
pod 'AxcAE_TabBar'
pod 'Masonry'
pod 'WRNavigationBar','~>1.2.0’
pod 'TYCyclePagerView'
pod 'SDWebImage', '>= 5.0.0'
pod 'MJExtension'
pod 'BRPickerView'
pod 'Mantle', '~> 2.1.0'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'AFNetworking', '<= 3.2.1'
pod 'MJRefresh'
pod 'MJExtension'

end
