source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'CyberGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for futures
pod 'JXCategoryView'
pod 'IQKeyboardManager'
pod 'AxcAE_TabBar'
pod 'Masonry'

end
